apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
spec:
  containers:
  - image: debian:latest
    name: volume-container-devops-1
    command: ["sleep", "36000"]
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/media
  - image: debian:latest
    name: volume-container-devops-2
    command: ["sleep", "36000"]
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/cluster
  volumes:
  - name: volume-share
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

k exec volume-share-devops -c volume-container-devops-1 -it -- /bin/bash